export TESTKIT_AWS_DEFAULT_REGION=us-east-1
export TESTKIT_AWS_KEYNAME=amancini
export TESTKIT_AWS_PURCHASE_TYPE=spot
export TESTKIT_AWS_REGION=us-east-1
#export TESTKIT_AWS_SECURITY_GROUP=sg-0e07f43528941f940
#export TESTKIT_AWS_SUBNET=subnet-0ea04ef42fb7b7304
#export TESTKIT_AWS_VPC_ID=vpc-04897724c62ebed5d
export TESTKIT_ENGINE=master
export TESTKIT_DRIVER=aws
export TESTKIT_SSH_KEYPATH=/home/$USER/.ssh/id_rsa


